backend:
  name: github
  repo: coloniaburjassot/coloniagatosburjassot
  branch: main
  auth_endpoint: https://coloniagatosburjassot.vercel.app/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gatos"
    label: "Gatos en adopción"
    folder: "gatos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Sexo", name: "sexo", widget: "select", options: ["Macho", "Hembra"] }
      - { label: "Fecha nacimiento", name: "fecha_nacimiento", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Esterilizado", name: "esterilizado", widget: "boolean", default: false }
      - { label: "Sociable", name: "sociable", widget: "boolean", default: false }
      - { label: "Estado", name: "estado", widget: "select", options: ["Sí", "No"], default: "No" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Descripción", name: "body", widget: "markdown" }

